library(pcaMethods)
library(readr)
library('dplyr')
library(tidyr)

file <- readline("Pls digita el nombre del archivo sin extension") 
df <- read_delim(c('/mnt/workstation/data/',file), delim = ",")
df <- data.frame(df)
numericos <- df[,4] %>% select_if(is.numeric)
result <- numericos %>% pca(., method="ppca", nPcs=3, seed=123)
cObs <- completeObs(result)
cObs <- data.frame(cObs, stringsAsFactors = TRUE)
df_complete <- cbind(df[2],cobs) 
write.csv(df_complete,c('/mnt/workstation/data/',file,'_df_Complete.csv')
