library(pcaMethods)
library(readr)
library('dplyr')
library(tidyr)

df <- read_delim('/mnt/workstation/data/Alomarrano/ToComplete_littlepig_con_PPCA.csv', delim = ",")
df <- data.frame(df)
numericos <- df[,c(1,seq(3,55))] %>% select_if(is.numeric)
result <- numericos %>% pca(., method="ppca", nPcs=3, seed=123)
cObs <- completeObs(result)
cObs <- data.frame(cObs, stringsAsFactors = TRUE)
df_complete <- cbind(df[2],cobs) 
write.csv(df_complete,'/mnt/workstation/data/Alomarrano/ToComplete_littlepig_con_PPCA.csv')
